# Generated by Django 3.0.6 on 2020-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del varietal (por ejemplo Torrontés, Cabernet Sauvignon, Merlot, etc ) ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del vino', max_length=30)),
                ('cosecha', models.IntegerField()),
                ('region', models.CharField(help_text='Ingrese la región del vino', max_length=30)),
                ('infoTEc', models.TextField(help_text='Ingrese la información técnica del vino', max_length=1000)),
                ('viticultura', models.TextField(help_text='Ingrese la Viticultura del vino', max_length=1000)),
                ('vinicultura', models.TextField(help_text='Ingrese la Vinicultura del vino', max_length=1000)),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Bodega')),
                ('varietal', models.ForeignKey(help_text='Seleccione un varietal para este vino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Varietal')),
            ],
        ),
    ]
