# Generated by Django 3.0.6 on 2020-06-09 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.FloatField()),
                ('ph', models.FloatField()),
                ('acidez_total', models.FloatField()),
                ('cierre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='vino',
            name='infoTEc',
        ),
        migrations.AddField(
            model_name='vino',
            name='infoTec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.InfoTec'),
        ),
    ]
